plugins {
    id 'application'
    id 'checkstyle'
    id 'com.github.spotbugs' version '5.0.13'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.guava)

    // Use JUnit 5 for testing
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.3'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = 'org.example.App'
}

checkstyle {
    toolVersion = "10.9.1"
    configFile = file("config/checkstyle/checkstyle.xml")
}

spotbugs {
    toolVersion = '5.0.13'
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

distributions {
    main {
        contents {
            from("src/main/resources")
        }
    }
}
