plugins {
    id 'application'
    id 'checkstyle'
    id 'jacoco' // Add JaCoCo plugin
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation(libs.guava)
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.3'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = 'org.example.App'
}

checkstyle {
    toolVersion = "10.9.1"
    configFile = file("config/checkstyle/checkstyle.xml")
}

jacoco {
    toolVersion = "0.8.12" // Specify the latest version
}

tasks.jacocoTestReport {
    dependsOn tasks.test // Ensure tests run first
    reports {
        xml.required = false
        html.required = true
    }
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
check.dependsOn jacocoTestReport
tasks.test.finalizedBy(tasks.jacocoTestReport)

distributions {
    main {
        contents {
            from("src/main/resources")
        }
    }
}
