import com.github.spotbugs.snom.SpotBugsTask

plugins {
    id 'application'
    id 'checkstyle'
    id 'com.github.spotbugs' version '6.0.25'
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation(libs.guava)
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.3'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

application {
    mainClass = 'org.example.App'
}

checkstyle {
    toolVersion = "10.9.1"
    configFile = file("config/checkstyle/checkstyle.xml")
}

spotbugs {
    toolVersion = '6.0.25'
}

tasks.withType(SpotBugsTask).configureEach {
    reports {
        html {
            required.set(true) // Set to true for generating HTML report
        }
        xml {
            required.set(false) // Set to false to disable XML report
        }
    }
}

tasks.test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}

distributions {
    main {
        contents {
            from("src/main/resources")
        }
    }
}
